<?php

include_once 'data_snapshots.fields.data_snapshot_data_source.inc';
include_once 'data_snapshots.fields.data_snapshot.inc';
include_once 'data_snapshots.field_groups.inc';

//function hook_ctools_plugin_api($module, $api) {
//  if ($module == 'field_group' && $api == 'field_group') {
//    return array('version' => 1);
//  }
//}


/*
function data_snapshots_theme_registry_alter(&$theme_registry) {
  $theme_registry["data_snapshot"]["path"] = drupal_get_path('module', 'data_snapshot');
}
*/

function data_snapshots_theme($existing, $type, $theme, $path) {
  return array (
                'node__data_snapshot' => array(
                                         'template' => 'node--data-snapshot',
                                         ),
                );
}

/*
function data_snapshots_theme() {
  return array(
    'data_snapshot' => array(
      'template' => 'data-snapshot',       // define xxx-xxx.tpl.php inside module
      'variables' => array('xxx' => null), // define $xxx so it will available in your xxx-xxx.tpl.php
    ),
  );
}
*/

/**
 * Implements hook_ctools_plugin_api().
 */
function data_snapshots_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == 'field_group' && $api == 'field_group') {
    return array('version' => 1);
  }    
}

function data_snapshots_node_info() {
  $items = array(
    'data_snapshot_data_source' => array(
      'name' => t('Data Snapshot Data Source'),
      'base' => 'data_snapshots',
      'description' => t('Content type for Data Snapshot Data Sources'),
      'has_title' => '1',
      'title_label' => t('Public Name for Dataset'),
      'help' => '',
    ),
    'data_snapshot' => array(
      'name' => t('Data Snapshot'),
      'base' => 'data_snapshots',
      'description' => t('Content type for Data Snapshots'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}


function data_snapshots_load($nodes) {
  //dsm("***********   data_snapshots_load   *************************\n");
  //dsm($nodes);
  //NOTE: hook_load() does not (need to) return anything
}



function data_snapshots_view($node, $view_mode) {
  //dsm("***********   data_snapshots_view   *************************\n");
  //dsm($node);
  return $node;
  //NOTE: hook_view MUST return $node
}


function data_snapshots_node_type_insert($content_type) {

  if ($content_type->type == 'data_snapshot') {
    foreach (data_snapshots_fields_data_snapshot() as $field) {
      field_create_field($field['field_config']);
      $instance = $field['field_instance'];
      $instance['entity_type'] = 'node';
      $instance['bundle'] = 'data_snapshot';
      field_create_instance($instance);
    }
  }

  if ($content_type->type == 'data_snapshot_data_source') {
    foreach (data_snapshots_fields_data_snapshot_data_source() as $field) {
      field_create_field($field['field_config']);
      $instance = $field['field_instance'];
      $instance['entity_type'] = 'node';
      $instance['bundle'] = 'data_snapshot_data_source';
      field_create_instance($instance);
    }
  }

}
