#! /bin/bash

drush -y en data_snapshots devel

drush vocimp --vocabulary_id=data_snapshot_data_set_frequency `pwd`/data_snapshot_data_set_frequency-vocab.csv flat

drush vocimp --vocabulary_id=data_snapshots_themes `pwd`/data_snapshots_themes-vocab.csv flat
